# Generated by Django 5.0.6 on 2026-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0018_alter_matrixentry_id_alter_projectvalidation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixentry',
            name='reference',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matrixentry',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
