# Generated by Django 5.0.6 on 2026-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0019_alter_matrixentry_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
