# Generated by Django 5.0.6 on 2026-06-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_asset_amortissement'),
        ('hr', '0005_candidate_evaluation_contract_document_and_more'),
        ('samples', '0021_bom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvalidation',
            name='accounting_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_projects', to='accounting.tiers'),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='actual_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='delivery_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='next_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='probability',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='sales_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='sales_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='sales_priority',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Normale'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='sales_reference',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectvalidation',
            name='sales_stage',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('opportunity', 'Opportunité'), ('quotation_sent', 'Devis envoyé'), ('negotiation', 'Négociation'), ('contract_signed', 'Contrat signé'), ('invoice_issued', 'Facture émise'), ('won', 'Gagné'), ('lost', 'Perdu')], db_index=True, default='prospect', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sales/documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='samples.projectvalidation')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_history', to='samples.projectvalidation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lead', 'Lead'), ('opportunity', 'Opportunity'), ('activity', 'Activity'), ('document', 'Document')], db_index=True, max_length=20)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(db_index=True, default='new', max_length=40)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sales/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounting_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='accounting.tiers')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_records', to='hr.employee')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_records', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_records', to='samples.salesrecord')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='downstream_records', to='samples.salesrecord')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='samples.projectvalidation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='samples.salesrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year'), ('custom', 'Custom')], default='month', max_length=20)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'month', 'quarter', 'employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['record_type', 'status'], name='samples_sal_record__cac3fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(fields=('employee', 'period_type', 'year', 'month', 'quarter', 'start_date', 'end_date'), name='unique_sales_target_period_per_employee'),
        ),
    ]
