# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location",
        ),
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("warehouse", "code")},
        ),
    ]
