# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledreport",
            name="recipients_emails",
            field=models.TextField(help_text="Comma-separated email addresses"),
        ),
    ]
