# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_orderline_unique_order_line_and_more"),
        ("production", "0003_workcenter_mo_routing"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stageevent",
            name="unique_line_stage",
        ),
        migrations.AlterUniqueTogether(
            name="stageevent",
            unique_together={("line", "stage")},
        ),
    ]
