# Generated by Django 5.0.6 on 2026-06-10 16:09

import accounting.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0002_remove_lot_unique_lot_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(blank=True, max_length=200)),
                ('forme_juridique', models.CharField(blank=True, help_text='SARL, SA, SAS, auto-entrepreneur…', max_length=50)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ice', models.CharField(blank=True, max_length=15, validators=[accounting.models.validate_ice], verbose_name='ICE')),
                ('if_fiscal', models.CharField(blank=True, max_length=20, verbose_name='Identifiant fiscal (IF)')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='Registre du commerce (RC)')),
                ('tp', models.CharField(blank=True, max_length=20, verbose_name='Taxe professionnelle (TP)')),
                ('cnss', models.CharField(blank=True, max_length=20, verbose_name='CNSS')),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('rib', models.CharField(blank=True, max_length=24, verbose_name='RIB')),
                ('tva_regime', models.CharField(choices=[('encaissement', 'Encaissement (droit commun)'), ('debit', 'Débits (sur option)')], default='encaissement', max_length=15)),
                ('tva_periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle (CA ≥ 1 MDH)'), ('trimestrielle', 'Trimestrielle')], default='trimestrielle', max_length=15)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='accounting/')),
                ('pied_de_page', models.TextField(blank=True, help_text='Texte libre ajouté en bas des PDF.')),
            ],
            options={
                'verbose_name': 'Profil société',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('mention_legale', models.CharField(blank=True, help_text='Mention portée sur la facture (ex : « Exonéré de TVA — art. 92 du CGI »).', max_length=255)),
            ],
            options={
                'verbose_name': 'Code TVA',
                'verbose_name_plural': 'Codes TVA',
                'ordering': ['-taux'],
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('raison_sociale', models.CharField(max_length=200)),
                ('est_client', models.BooleanField(default=True)),
                ('est_fournisseur', models.BooleanField(default=False)),
                ('est_particulier', models.BooleanField(default=False)),
                ('ice', models.CharField(blank=True, max_length=15, validators=[accounting.models.validate_ice], verbose_name='ICE')),
                ('if_fiscal', models.CharField(blank=True, max_length=20, verbose_name='Identifiant fiscal (IF)')),
                ('rc', models.CharField(blank=True, max_length=20, verbose_name='RC')),
                ('tp', models.CharField(blank=True, max_length=20, verbose_name='TP')),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Maroc', max_length=100)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delai_paiement_jours', models.PositiveIntegerField(default=0, help_text='0 = comptant ; 30/60/90 = échéance en jours.')),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture'), ('avoir', 'Avoir'), ('facture_achat', "Facture d'achat"), ('avoir_achat', "Avoir d'achat")], db_index=True, max_length=20)),
                ('numero', models.CharField(blank=True, help_text='Attribué automatiquement à la validation.', max_length=20, null=True, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validé'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('expire', 'Expiré'), ('partiellement_payee', 'Partiellement payé'), ('payee', 'Payé'), ('annulee', 'Annulé')], db_index=True, default='brouillon', max_length=25)),
                ('date_emission', models.DateField(default=django.utils.timezone.localdate)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('reference_externe', models.CharField(blank=True, max_length=50)),
                ('objet', models.CharField(blank=True, max_length=255)),
                ('ras_type', models.CharField(choices=[('aucune', 'Aucune'), ('is_ht', 'RAS sur le HT (IS / honoraires)'), ('tva', 'RAS sur la TVA')], default='aucune', max_length=10)),
                ('ras_taux', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ras_montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('document_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_derives', to='accounting.document')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL)),
                ('tiers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounting.tiers')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_emission', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture'), ('avoir', 'Avoir'), ('facture_achat', "Facture d'achat"), ('avoir_achat', "Avoir d'achat")], max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Séquence de numérotation',
                'unique_together': {('doc_type', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mode', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('espece', 'Espèces'), ('effet', 'Effet de commerce'), ('carte', 'Carte bancaire'), ('compensation', 'Compensation')], default='virement', max_length=15)),
                ('reference', models.CharField(blank=True, help_text='N° de chèque, référence de virement…', max_length=64)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('timbre_montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='accounting.document')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_document', to='storage.article')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.document')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.taxcode')),
            ],
            options={
                'verbose_name': 'Ligne de document',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
