# Generated by Django 5.0.6 on 2026-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_seed_tax_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='site_web',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
