# Generated by Django 5.0.6 on 2026-06-11 09:13

import accounting.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_companyprofile_site_web'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=10, unique=True, validators=[accounting.models.validate_numero_compte])),
                ('intitule', models.CharField(max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('vente', 'Ventes'), ('achat', 'Achats'), ('tresorerie', 'Trésorerie'), ('od', 'Opérations diverses')], default='od', max_length=15)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='compte_contrepartie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='accounting.comptecomptable'),
        ),
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('cloture', 'Clôturé')], default='ouvert', max_length=10)),
                ('cloture_at', models.DateTimeField(blank=True, null=True)),
                ('cloture_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices_clotures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('date_ecriture', models.DateField(db_index=True)),
                ('libelle', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures_creees', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ecriture', to='accounting.document')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecriture', to='accounting.paiement')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='accounting.journal')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'ordering': ['-date_ecriture', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='accounting.comptecomptable')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounting.ecriturecomptable')),
                ('tiers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture', to='accounting.tiers')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'ordering': ['ecriture', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField()),
                ('dernier_numero', models.PositiveIntegerField(default=0)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='accounting.journal')),
            ],
            options={
                'unique_together': {('journal', 'annee')},
            },
        ),
    ]
