# Generated by Django 5.0.6 on 2026-06-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_leaverequest_document_alter_employee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
