# Generated by Django 5.0.6 on 2026-06-10 09:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lot',
            name='unique_lot_article',
        ),
        migrations.RemoveConstraint(
            model_name='placement',
            name='unique_placement_code',
        ),
        migrations.AddField(
            model_name='article',
            name='actif',
            field=models.BooleanField(default=True, help_text="Décochez pour désactiver sans supprimer l'historique."),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantite_reservee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantité réservée (allouée) sur ce stock, non disponible pour sortie/transfert.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='placement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='lot',
            unique_together={('article', 'numero_lot')},
        ),
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('entrepot', 'code_emplacement')},
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', False)), fields=('article', 'placement', 'lot'), name='unique_stock_with_lot'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', True)), fields=('article', 'placement'), name='unique_stock_without_lot'),
        ),
    ]
