# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderline_sort_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderline",
            name="unique_order_line",
        ),
        migrations.AlterUniqueTogether(
            name="orderline",
            unique_together={("order", "n_serie")},
        ),
    ]
