# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="articlerevision",
            name="unique_article_revision",
        ),
        migrations.AlterUniqueTogether(
            name="articlerevision",
            unique_together={("article", "revision_no")},
        ),
    ]
