# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_articlerevision_unique_article_revision_and_more"),
        ("plm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billofmaterials",
            name="unique_bom_revision",
        ),
        migrations.AlterUniqueTogether(
            name="billofmaterials",
            unique_together={("article", "revision")},
        ),
    ]
