# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="apn",
            name="workflow_apn_work_order_apn_code_uniq",
        ),
        migrations.AlterUniqueTogether(
            name="apn",
            unique_together={("work_order", "apn_code")},
        ),
    ]
