# Generated by Django 5.0.6 on 2026-06-11 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_candidate_evaluation_contract_document_and_more'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logisticstaskhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Historique de tâche', 'verbose_name_plural': 'Historiques des tâches'},
        ),
        migrations.CreateModel(
            name='LogisticsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('assignment', 'Affectation'), ('modification', 'Modification'), ('deadline', 'Échéance proche'), ('completed', 'Tâche terminée'), ('cancelled', 'Tâche annulée'), ('comment', 'Nouveau commentaire'), ('attachment', 'Nouvelle pièce jointe')], default='modification', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logistics_notifications', to='hr.employee')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='logistics.logisticstask')),
            ],
            options={
                'verbose_name': 'Notification logistique',
                'verbose_name_plural': 'Notifications logistiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='logistics_l_recipie_8a1ed1_idx'), models.Index(fields=['employee', 'is_read'], name='logistics_l_employe_cf0b80_idx'), models.Index(fields=['created_at'], name='logistics_l_created_d378ea_idx')],
            },
        ),
    ]
