# Generated by Django 5.0.6 on 2026-06-11 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_logisticstaskhistory_options_and_more'),
        ('storage', '0002_remove_lot_unique_lot_article_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='destination_type',
            field=models.CharField(choices=[('warehouse', 'Entrepôt'), ('external', 'Destination externe')], default='warehouse', max_length=20),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='external_destination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Destination externe'),
        ),
        migrations.AlterField(
            model_name='warehousetransfer',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_logistics_transfers', to='storage.entrepot', verbose_name='Entrepôt destination'),
        ),
        migrations.CreateModel(
            name='LogisticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('report_type', models.CharField(choices=[('delivery', 'Livraison'), ('shipment', 'Expédition'), ('transfer', 'Transfert'), ('vehicle', 'Véhicule'), ('task', 'Tâche'), ('incident', 'Incident'), ('other', 'Autre')], default='other', max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
