# Generated by Django 5.0.6 on 2026-06-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_warehousetransfer_destination_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='external_address',
            field=models.TextField(blank=True, verbose_name='Adresse externe'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='external_agency',
            field=models.CharField(blank=True, max_length=200, verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='external_client',
            field=models.CharField(blank=True, max_length=200, verbose_name='Client externe'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='external_site',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chantier'),
        ),
    ]
