# Generated by Django 5.0.6 on 2026-06-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_warehousetransfer_external_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsreport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_tasks', to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='transport_type',
            field=models.CharField(choices=[('own_vehicle', 'Véhicule interne'), ('service', 'Service externe')], default='own_vehicle', max_length=20),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to='logistics.vehicle'),
        ),
    ]
