# Generated by Django 5.0.6 on 2026-06-11 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_logisticsreport_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsreport',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='logisticstask',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_tasks', to='logistics.vehicle'),
        ),
    ]
