# Generated by Django 5.0.6 on 2026-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_logisticsreport_vehicle_logisticstask_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='service_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
