# Generated by Django 5.0.6 on 2026-06-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_warehousetransfer_service_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransfer',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers', to='logistics.driver'),
        ),
    ]
