# Generated by Django 5.0.6 on 2026-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attachment",
            new_name="documents_a_content_028f26_idx",
            old_name="attachment_ct_obj_idx",
        ),
    ]
